# docker build -t blk-hacking-ind-ketan-deshmukh .

FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY target/BlackRock-Challenge-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 5477

ENTRYPOINT ["java","-jar","app.jar"]